module.exports = function(grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
    concat: {
            css: {
           src: [
                 'src/*.css'
                ],
            dest: 'dist/theme.css'
        },
        js : {
            src : [
                'src/*.js'
            ],
            dest : 'dist/theme.js'
        }
    },
    cssmin : {
            css:{
                src: 'dist/theme.css',
                dest: 'dist/theme.css'
            }
        },
    uglify : {
        js: {
            files: {
                'dist/theme.js' : [ 'dist/theme.js' ]
            }
        }
    },
    'gh-pages': {
      options: {
        base: 'dist' ,
        message: 'Generated by grunt gh-pages'
      } ,
      src: ['**/*']
    }

    });
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-contrib-watch');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-gh-pages');
    grunt.registerTask('default', [ 'concat:css', 'cssmin:css', 'concat:js', 'uglify:js' ]);
    grunt.registerTask ('deploy', ['default', 'gh-pages']);
};
